defaults:
  - base
  - dataset: mmlb
  - _self_

run-name: mmlb-baseline

# add img des
dom_image_description:
  cuda_visible_devices: '0'
  dom_method: mineru # chatdoc, docling
  agents:
    - agent: imgdes_agent
      model: qwen2vl

dataset:
  # dom_path: ${dataset.base_dir}/tmp/${dataset.name}/tree_chatdoc
  # dom_output_path: ${dataset.base_dir}/tmp/${dataset.name}/tree_chatdoc_with_descriptions_path
  dom_path: ${dataset.base_dir}/MinerU_MMLB
  dom_output_path: ${dataset.base_dir}/tmp/${dataset.name}/tree_mineru_with_descriptions_path