name: base
use_top-k: 1
question_key: question
gt_key: answer
page_id_key: page_ids
max_page: 1000
max_character_per_page: 100000
data_dir: ${dataset.base_dir}/${dataset.name}
extract_path: ${dataset.base_dir}/tmp/${dataset.name}
document_path: ${dataset.base_dir}/${dataset.name}/documents
sample_path: ${dataset.data_dir}/samples.json
sample_with_retrieval_path: ${dataset.data_dir}/sample-with-retrieval-results.json

# DOM path
dom_path: ${dataset.base_dir}/tmp/${dataset.name}/tree_chatdoc
dom_output_path: ${dataset.base_dir}/tmp/${dataset.name}/tree_chatdoc_with_descriptions_path