defaults:
  - base
  - _self_

name: MMLongBench

# Block tree构建配置
block_tree:
  max_words: 256              # 单个block最大词数
  min_words: 64               # 最小词数（过小则合并）
  include_parent_context: true # 是否在子block中包含父章节标题
  
  input_path: ${dataset.base_dir}/tmp/${dataset.name}/tree_chatdoc_with_descriptions_path
  output_path: ${dataset.base_dir}/tmp/${dataset.name}/blocks